version: 0.2

phases:
  install:
    commands:
    - echo installing maven...
    - yum install -y maven
  build:
    commands:
      - echo Build completed on `date`
      - cd /home/ec2-user/java-app/java-app-cicd/
      - echo 'pwd'
      - mvn clean test package
      

artifacts:
  files:
    - '**/*'
